/* hexlib/runtime/skel/hexlib_dsp.h -- the DSP-side contract.
 *
 * THE HOST WRITES FDS AND OFFSETS. THE DSP WRITES ADDRESSES. `hexlib_buf_desc.base`
 * and `hexlib_tensor.data` are scratch fields this side fills in; a host that put
 * an address in either would produce code that works on the simulator -- where
 * host and DSP share one address space -- and fails instantly on silicon. There is
 * no field on the wire for an address, which is what makes a simulator result
 * transferable.
 *
 * Adapted in shape from llama.cpp ggml-hexagon's htp-ops.h (MIT); see
 * ATTRIBUTION.md. Two things are deliberately NOT adapted: ne/nb strides (hexlib
 * uses an enumerated layout, so un-repacked weights are a plan-time error rather
 * than silent corruption, and strides cannot describe a VTCM-resident tile of a
 * DDR tensor) and the ggml opcode enum.
 */
#ifndef HEXLIB_DSP_H
#define HEXLIB_DSP_H

#include <stddef.h>
#include <stdint.h>

#define HEXLIB_BATCH_MAGIC   0x424C5848u   /* 'HXLB' little-endian */
#define HEXLIB_BATCH_VERSION 1

#define HEXLIB_MAX_BUFS 8
#define HEXLIB_MAX_SRC 6
#define HEXLIB_MAX_DST 4
#define HEXLIB_MAX_PARAMS 16
#define HEXLIB_MAX_TENSORS 512

/* OK IS 1, NOT 0. A response buffer that is never written is all zeros, and zero
 * must not read as success -- this project has been bitten four times by absence
 * reported as success, including a device-farm job that ran no tests and passed. */
enum hexlib_dsp_status {
    HEXLIB_DSP_OK = 1,
    HEXLIB_DSP_ERR_INTERNAL = 2,
    HEXLIB_DSP_ERR_BAD_MAGIC = 3,
    HEXLIB_DSP_ERR_BAD_VERSION = 4,
    HEXLIB_DSP_ERR_TRUNCATED = 5,
    HEXLIB_DSP_ERR_INVAL_PARAMS = 6,
    HEXLIB_DSP_ERR_UNMAPPED = 7,
    HEXLIB_DSP_ERR_NO_MMAP_SLOT = 8,
    HEXLIB_DSP_ERR_MMAP_FAILED = 9,
    HEXLIB_DSP_ERR_NO_KERNEL = 10,
    HEXLIB_DSP_ERR_VTCM_TOO_SMALL = 11,
    HEXLIB_DSP_ERR_VTCM_RECLAIMED = 12,
    HEXLIB_DSP_ERR_REQUIRES = 13,
    HEXLIB_DSP_ERR_NOT_STARTED = 14,
};

struct hexlib_batch_hdr {
    uint32_t magic;
    uint32_t version;
    uint32_t total_size;
    uint32_t n_bufs;
    uint32_t n_tensors;
    uint32_t n_ops;
    uint32_t off_bufs;
    uint32_t off_tensors;
    uint32_t off_ops;
    uint32_t flags;
};

struct hexlib_buf_desc {
    uint64_t base;   /* DSP-SIDE SCRATCH. Host writes 0. */
    uint64_t size;
    uint32_t fd;
    uint32_t flags;
};

struct hexlib_tensor {
    uint32_t bi;
    uint32_t offset;
    uint32_t nbytes;
    uint32_t dtype;
    uint32_t layout;
    uint32_t ne[4];
    uint32_t data;   /* DSP-SIDE SCRATCH. Host writes 0. */
    uint32_t pad;
};

struct hexlib_op_desc {
    uint32_t kind;
    uint32_t flags;
    int32_t  params[HEXLIB_MAX_PARAMS];
    uint16_t src[HEXLIB_MAX_SRC];
    uint16_t dst[HEXLIB_MAX_DST];
};

struct hexlib_batch_rsp_hdr {
    uint32_t magic;
    uint32_t version;
    uint32_t status;
    uint32_t n_ops;
    uint64_t cycles_total;
    uint32_t arch;
    uint32_t pad;
};

struct hexlib_op_result {
    uint32_t kind;
    uint32_t status;
    uint64_t cycles;
};

/* The kernel ABI. `int`, not `void`: a kernel that cannot serve a request says so
 * rather than producing a plausible wrong answer. */
typedef struct {
    void       *buf[HEXLIB_MAX_BUFS];
    uint32_t    ne[HEXLIB_MAX_BUFS][4];
    uint32_t    dtype[HEXLIB_MAX_BUFS];
    uint32_t    layout[HEXLIB_MAX_BUFS];
    uint32_t    n_buf;
    uint8_t    *vtcm;
    size_t      vtcm_size;
    const void *params;
    uint32_t    n_threads;
} hexlib_args;

typedef int (*hexlib_kernel_fn)(const hexlib_args *);

struct hexlib_kernel_entry {
    uint32_t          kind;
    const char       *name;
    hexlib_kernel_fn  fn;
};

/* Generated by hexlib/runtime/genentry.py. */
extern const struct hexlib_kernel_entry hexlib_kernel_table[];
extern const uint32_t hexlib_kernel_table_len;

#endif /* HEXLIB_DSP_H */
